### PR TITLE
Some fixes

### LINKED ISSUE #3: Accept and Reject button not working

### LINKED ISSUE #9: SQL Injection
- Switch to parameterized query

### LINKED ISSUE #17: [DepShield] (CVSS 6.5) Vulnerability due to usage of mysql:2.17.1
**Vulnerabilities**

DepShield reports that this application's usage of [mysql:2.17.1](https://ossindex.sonatype.org/component/pkg:npm/mysql@2.17.1) results in the following vulnerability(s):

- (CVSS **6.5**) [CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')](https://ossindex.sonatype.org/vuln/e27505b2-b0b7-4863-a3f5-8df961db080f)

<sub>This is an automated GitHub Issue created by Sonatype DepShield. Details on managing GitHub Apps, including DepShield, are available for [personal](https://help.github.com/articles/managing-your-personal-account-s-apps/) and [organization](https://help.github.com/articles/managing-your-organization-s-apps/) accounts. Please submit questions or feedback about DepShield to the [Sonatype DepShield Community](https://community.sonatype.com/c/depshield).</sub>

### PR DESCRIPTION
**Pull request by aravindvnair99**
- New DB
- Fixed calendar
- Refactored
- Added approve request
- Added reject request
- Enhance security
- Update the ER diagram
- Cleanup
- Set limit for dates
- Select at least one hall and slot
- Fixed #9 , fixed #17, fixed #3

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -0,0 +1,354 @@
...
+// 			list[parts.shift().trim()] = decodeURI(parts.join("="));
+// 		});
+
+// 	return list;
+// }
+// var hall_id = parseCookies(req).hall_id;
+app.get("/", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 50
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 2]
```diff
@@ -0,0 +1,354 @@
...
+						"delete from events where id = ?",
+						result[0].event_id,
+						err => {
+							if (!err) {
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 3]
```diff
@@ -0,0 +1,354 @@
...
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 4]
```diff
@@ -0,0 +1,354 @@
...
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
+										);
+										res.redirect("/dashboard");
+									} else {
+										console.log(err);
+										res.status(500).render("error", {
+											error_message:
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 5]
```diff
@@ -0,0 +1,354 @@
...
+			if (!err) {
+				if (rows.length > 0) {
+					if (
+						password ===
+						AES.decrypt(rows[0].password, `${process.env.AES_key}`)
+					) {
+						req.session.user = rows[0];
+						res.redirect("/dashboard");
+					} else {
+						console.log("Invalid password");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 6]
```diff
@@ -0,0 +1,354 @@
...
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'user_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 7]
```diff
@@ -0,0 +1,354 @@
...
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
+		var slot_hall = "";
+		for (var i = 1; i <= 7; i++)
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'slot_hall' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 8]
```diff
@@ -0,0 +1,354 @@
...
+								event_id: event_id[0].id,
+								slot_hall: slot_hall
+							};
+							con.query(
+								"insert into booking set ?",
+								booking_obj,
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 9]
```diff
@@ -0,0 +1,354 @@
...
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 10]
```diff
@@ -0,0 +1,354 @@
...
+							res.status(500).render("error", {
+								error_message: "Retrieving event_id failed!"
+							});
+						}
+					}
+				);
+			} else {
+				console.log(err);
+				res.status(500).render("error", {
+					error_message: "Inserting into event failed!"
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 11]
```diff
@@ -0,0 +1,354 @@
...
+	}
+});
+app.get("/dashboard_facility_table", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking;", function(err, booking_data) {
+			con.query("select * from events;", function(err, events_data) {
+				res.render("dashboard_facility_table", {
+					res: req.session.user,
+					booking_data,
+					events_data
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'events_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 12]
```diff
@@ -0,0 +1,354 @@
...
+	bodyParser.urlencoded({
+		extended: false
+	})
+);
+app.set("port", process.env.node_port);
+app.use(express.static(__dirname + "/public"));
+app.set("views", path);
+app.set("view engine", "ejs");
+app.listen(app.get("port"), () => {
+	console.log("App is running on port", app.get("port"));
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 13]
```diff
@@ -0,0 +1,354 @@
...
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					function(err, event_id) {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'user_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 14]
```diff
@@ -0,0 +1,354 @@
...
+		res.redirect("/dashboard");
+	} else res.render("login");
+});
+app.get("/dashboard", (req, res) => {
+	if (req.session.user) {
+		if (req.session.user.role === "teacher") {
+			con.query(
+				"select * from booking where user_id= ?",
+				req.session.user.id,
+				function(err, booking_data) {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 15]
```diff
@@ -0,0 +1,354 @@
...
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					function(err, event_id) {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
+								event_id: event_id[0].id,
+								slot_hall: slot_hall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 16]
```diff
@@ -0,0 +1,354 @@
...
+	if (req.session.user) {
+		con.query(
+			"select event_id from booking where id = ?",
+			req.body.booking_id,
+			(err, result) => {
+				if (result) {
+					con.query(
+						"delete from events where id = ?",
+						result[0].event_id,
+						err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 17]
```diff
@@ -0,0 +1,354 @@
...
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
+		};
+		con.query("insert into events set ?", event_obj, err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 18]
```diff
@@ -0,0 +1,354 @@
...
+		res.redirect("/login");
+	}
+});
+app.get("/dashboard_facility_table", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking;", function(err, booking_data) {
+			con.query("select * from events;", function(err, events_data) {
+				res.render("dashboard_facility_table", {
+					res: req.session.user,
+					booking_data,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 19]
```diff
@@ -0,0 +1,354 @@
...
+					);
+				} else res.send(JSON.stringify(err.code));
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateStatus", (req, res) => {
+	console.log(req.body.type);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 20]
```diff
@@ -0,0 +1,354 @@
...
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
+												`${req.body.booking_id} is deleted`
+											);
+											res.send(JSON.stringify(result));
+										} else
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 21]
```diff
@@ -0,0 +1,354 @@
...
+						});
+					}
+				} else {
+					console.log("Username not found!");
+					res.status(401).render("error", {
+						error_message: "Authentication error!"
+					});
+				}
+			} else {
+				console.log("Username not found!");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 22]
```diff
@@ -0,0 +1,354 @@
...
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'date_wanted' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 23]
```diff
@@ -0,0 +1,354 @@
...
+				});
+			}
+		});
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateBooking", (req, res) => {
+	if (req.session.user) {
+		console.log("updateRequest");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 24]
```diff
@@ -0,0 +1,354 @@
...
+// var hall_id = parseCookies(req).hall_id;
+app.get("/", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("login");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 50
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 25]
```diff
@@ -0,0 +1,376 @@
...
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
+		};
+		con.query("insert into events set ?", event_obj, err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 26]
```diff
@@ -0,0 +1,376 @@
...
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					function(err, event_id) {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
+								event_id: event_id[0].id,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 27]
```diff
@@ -0,0 +1,376 @@
...
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 28]
```diff
@@ -0,0 +1,376 @@
...
+						error_message: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 29]
```diff
@@ -0,0 +1,376 @@
...
+			booking_data
+		) {
+			con.query("select * from events where id=30;", function(
+				err,
+				events_data
+			) {
+				console.log({ booking_data }, { events_data });
+				res.render("requestUpdate", {
+					res: req.session.user,
+					booking_data,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 30]
```diff
@@ -0,0 +1,376 @@
...
+				} else {
+					console.log("Username not found!");
+					res.status(401).render("error", {
+						error_message: "Authentication error!"
+					});
+				}
+			} else {
+				console.log("Username not found!");
+				res.status(401).render("error", {
+					error_message: "Authentication error!"
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 31]
```diff
@@ -0,0 +1,376 @@
...
+						} else {
+							console.log(err);
+							res.status(500).render("error", {
+								error_message: "Retrieving event_id failed!"
+							});
+						}
+					}
+				);
+			} else {
+				console.log(err);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 32]
```diff
@@ -0,0 +1,376 @@
...
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
+		var slot_hall = "";
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'slot_hall' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 33]
```diff
@@ -0,0 +1,376 @@
...
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 34]
```diff
@@ -0,0 +1,376 @@
...
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 35]
```diff
@@ -0,0 +1,376 @@
...
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 36]
```diff
@@ -0,0 +1,376 @@
...
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 37]
```diff
@@ -0,0 +1,376 @@
...
+			});
+		});
+	} else {
+		res.redirect("/login");
+	}
+});
+app.get("/dashboard_facility_table", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking;", function(err, booking_data) {
+			con.query("select * from events;", function(err, events_data) {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'events_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 38]
```diff
@@ -0,0 +1,376 @@
...
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
+		var slot_hall = "";
+		for (var i = 1; i <= 7; i++)
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'for' condition. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 39]
```diff
@@ -0,0 +1,376 @@
...
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("login");
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 40]
```diff
@@ -0,0 +1,376 @@
...
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 41]
```diff
@@ -0,0 +1,376 @@
...
+	if (req.session.user) {
+		if (req.session.user.role === "teacher") {
+			con.query(
+				"select * from booking where user_id= ?",
+				req.session.user.id,
+				function(err, booking_data) {
+					con.query(
+						"select * from events where user_id= ?",
+						req.session.user.id,
+						function(err, events_data) {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'events_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 42]
```diff
@@ -0,0 +1,376 @@
...
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
+												`${req.body.booking_id} is deleted`
+											);
+											res.send(JSON.stringify(result));
+										} else
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 43]
```diff
@@ -0,0 +1,376 @@
...
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'user_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 44]
```diff
@@ -0,0 +1,376 @@
...
+								event_id: event_id[0].id,
+								slot_hall: slot_hall
+							};
+							con.query(
+								"insert into booking set ?",
+								booking_obj,
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 45]
```diff
@@ -0,0 +1,376 @@
...
+											error_message:
+												"Inserting into booking failed!"
+										});
+									}
+								}
+							);
+						} else {
+							console.log(err);
+							res.status(500).render("error", {
+								error_message: "Retrieving event_id failed!"
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 46]
```diff
@@ -0,0 +1,376 @@
...
+		) {
+			con.query("select * from events where id=30;", function(
+				err,
+				events_data
+			) {
+				console.log({ booking_data }, { events_data });
+				res.render("requestUpdate", {
+					res: req.session.user,
+					booking_data,
+					events_data
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'events_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 47]
```diff
@@ -0,0 +1,376 @@
...
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					function(err, event_id) {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
+								event_id: event_id[0].id,
+								slot_hall: slot_hall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 27 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 48]
```diff
@@ -0,0 +1,376 @@
...
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
+										);
+										res.redirect("/dashboard");
+									} else {
+										console.log(err);
+										res.status(500).render("error", {
+											error_message:
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 50
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 49]
```diff
@@ -0,0 +1,380 @@
...
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 50]
```diff
@@ -0,0 +1,380 @@
...
+							res.status(500).render("error", {
+								error_message: "Retrieving event_id failed!"
+							});
+						}
+					}
+				);
+			} else {
+				console.log(err);
+				res.status(500).render("error", {
+					error_message: "Inserting into event failed!"
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 51]
```diff
@@ -0,0 +1,380 @@
...
+app.get("/requestUpdate", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking where id=4;", (err, booking_data) => {
+			con.query(
+				"select * from events where id=30;",
+				(err, events_data) => {
+					res.render("requestUpdate", {
+						res: req.session.user,
+						booking_data,
+						events_data
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'events_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 52]
```diff
@@ -0,0 +1,380 @@
...
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
+		var slot_hall = "";
+		for (var i = 1; i <= 7; i++)
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'slot_hall' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 53]
```diff
@@ -0,0 +1,380 @@
...
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
+								event_id: event_id[0].id,
+								slot_hall: slot_hall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 54]
```diff
@@ -0,0 +1,380 @@
...
+});
+app.post("/onLogin", (req, res) => {
+	var username = req.body.username;
+	var password = req.body.password;
+	con.query(
+		"select * from users where username='" + username + "';",
+		(err, rows) => {
+			if (!err) {
+				if (rows.length > 0) {
+					if (
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Potential timing attack, left side: true (security/detect-possible-timing-attacks)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 55]
```diff
@@ -0,0 +1,380 @@
...
+});
+app.get("/requestUpdate", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking where id=4;", (err, booking_data) => {
+			con.query(
+				"select * from events where id=30;",
+				(err, events_data) => {
+					res.render("requestUpdate", {
+						res: req.session.user,
+						booking_data,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 56]
```diff
@@ -0,0 +1,380 @@
...
+						});
+					}
+				} else {
+					console.log("Username not found!");
+					res.status(401).render("error", {
+						error_message: "Authentication error!"
+					});
+				}
+			} else {
+				console.log("Username not found!");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 49 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 57]
```diff
@@ -0,0 +1,380 @@
...
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("login");
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 58]
```diff
@@ -0,0 +1,380 @@
...
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE user_id= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
+						if (!err) {
+							var booking_obj = {
+								user_id: user_id,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'user_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 59]
```diff
@@ -0,0 +1,380 @@
...
+						error_message: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 60]
```diff
@@ -0,0 +1,380 @@
...
+			if (!err) {
+				if (rows.length > 0) {
+					if (
+						password ===
+						AES.decrypt(rows[0].password, `${process.env.AES_key}`)
+					) {
+						req.session.user = rows[0];
+						res.redirect("/dashboard");
+					} else {
+						console.log("Invalid password");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 61]
```diff
@@ -0,0 +1,380 @@
...
+						} else {
+							console.log(err);
+							res.status(500).render("error", {
+								error_message: "Retrieving event_id failed!"
+							});
+						}
+					}
+				);
+			} else {
+				console.log(err);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Unexpected console statement. (no-console)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 62]
```diff
@@ -0,0 +1,380 @@
...
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var user_id = req.session.user.id;
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'user_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 63]
```diff
@@ -0,0 +1,380 @@
...
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
+			user_id: user_id
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 64]
```diff
@@ -0,0 +1,380 @@
...
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 65]
```diff
@@ -0,0 +1,380 @@
...
+	if (req.session.user) {
+		con.query(
+			"select event_id from booking where id = ?",
+			req.body.booking_id,
+			(err, result) => {
+				if (result) {
+					con.query(
+						"delete from events where id = ?",
+						result[0].event_id,
+						err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 66]
```diff
@@ -0,0 +1,380 @@
...
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 67]
```diff
@@ -0,0 +1,380 @@
...
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
+												`${req.body.booking_id} is deleted`
+											);
+											res.send(JSON.stringify(result));
+										} else
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 68]
```diff
@@ -0,0 +1,380 @@
...
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
+										);
+										res.redirect("/dashboard");
+									} else {
+										console.log(err);
+										res.status(500).render("error", {
+											error_message:
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'error_message' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 69]
```diff
@@ -0,0 +1,380 @@
...
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 70]
```diff
@@ -0,0 +1,380 @@
...
+				});
+			});
+		});
+	} else {
+		res.redirect("/login");
+	}
+});
+app.get("/dashboard_facility_table", (req, res) => {
+	if (req.session.user) {
+		con.query("select * from booking;", (err, booking_data) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_data' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 71]
```diff
@@ -0,0 +1,380 @@
...
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slot_hall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 72]
```diff
@@ -0,0 +1,380 @@
...
+			title: title,
+			club: club,
+			requirements: requirements,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 28
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 73]
```diff
@@ -0,0 +1,380 @@
...
+			date_wanted: date_wanted,
+			userID: userID
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 74]
```diff
@@ -0,0 +1,380 @@
...
+								event_id: event_id[0].id,
+								slotHall: slotHall
+							};
+							con.query(
+								"insert into booking set ?",
+								booking_obj,
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.event_id} into booking.`
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 75]
```diff
@@ -0,0 +1,380 @@
...
+			);
+		} else if (req.body.type === "reject") {
+			con.query(
+				'update booking set status="Rejected" where id = ?',
+				req.body.booking_id,
+				(err, result) => {
+					if (!err) {
+						console.log(`${req.body.booking_id} is rejected`);
+						res.send(JSON.stringify(result));
+					} else res.send(JSON.stringify(err.code));
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 76]
```diff
@@ -0,0 +1,380 @@
...
+// 			list[parts.shift().trim()] = decodeURI(parts.join("="));
+// 		});
+
+// 	return list;
+// }
+// var hall_id = parseCookies(req).hall_id;
+app.get("/", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 77]
```diff
@@ -0,0 +1,380 @@
...
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var userID = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
+		var slotHall = "";
+		for (var i = 1; i <= 7; i++)
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'for' condition. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 78]
```diff
@@ -0,0 +1,380 @@
...
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
+						if (!err) {
+							var booking_obj = {
+								userID: userID,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 79]
```diff
@@ -0,0 +1,380 @@
...
+// var hall_id = parseCookies(req).hall_id;
+app.get("/", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("index");
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else res.render("login");
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 80]
```diff
@@ -0,0 +1,380 @@
...
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
+												`${req.body.booking_id} is deleted`
+											);
+											res.send(JSON.stringify(result));
+										} else
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 81]
```diff
@@ -0,0 +1,380 @@
...
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 82]
```diff
@@ -0,0 +1,380 @@
...
+			requirements: requirements,
+			details: details,
+			date_wanted: date_wanted,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'date_wanted' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 83]
```diff
@@ -0,0 +1,380 @@
...
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 84]
```diff
@@ -0,0 +1,380 @@
...
+	if (req.session.user) {
+		con.query(
+			"select event_id from booking where id = ?",
+			req.body.booking_id,
+			(err, result) => {
+				if (result) {
+					con.query(
+						"delete from events where id = ?",
+						result[0].event_id,
+						err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 85]
```diff
@@ -0,0 +1,380 @@
...
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 86]
```diff
@@ -0,0 +1,380 @@
...
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
+						if (!err) {
+							var booking_obj = {
+								userID: userID,
+								event_id: event_id[0].id,
+								slotHall: slotHall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 87]
```diff
@@ -0,0 +1,380 @@
...
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var userID = req.session.user.id;
+		var date_wanted = req.body.date_wanted;
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'date_wanted' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 88]
```diff
@@ -0,0 +1,380 @@
...
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 89]
```diff
@@ -0,0 +1,380 @@
...
+			details: details,
+			date_wanted: date_wanted,
+			userID: userID
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 90]
```diff
@@ -0,0 +1,380 @@
...
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, event_id) => {
+						if (!err) {
+							var booking_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 82 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 91]
```diff
@@ -0,0 +1,380 @@
...
+								userID: userID,
+								event_id: event_id[0].id,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_id' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 92]
```diff
@@ -0,0 +1,380 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 93]
```diff
@@ -0,0 +1,380 @@
...
+				(err, result) => {
+					if (!err) {
+						console.log(`${req.body.booking_id} is approved`);
+						res.send(JSON.stringify(result));
+					} else res.send(JSON.stringify(err.code));
+				}
+			);
+		} else if (req.body.type === "reject") {
+			con.query(
+				'update booking set status="Rejected" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 94]
```diff
@@ -0,0 +1,380 @@
...
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateStatus", (req, res) => {
+	console.log(req.body.type);
+	if (req.session.user) {
+		if (req.body.type === "approve") {
+			con.query(
+				'update booking set status="Approved" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 57 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 95]
```diff
@@ -0,0 +1,380 @@
...
+				if (req.body[`cell${j}${i}`]) {
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 24
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 96]
```diff
@@ -0,0 +1,380 @@
...
+								eventID: eventID[0].id,
+								slotHall: slotHall
+							};
+							con.query(
+								"insert into booking set ?",
+								booking_obj,
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.eventID} into booking.`
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 97]
```diff
@@ -0,0 +1,380 @@
...
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			dateWanted: dateWanted,
+			userID: userID
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 98]
```diff
@@ -0,0 +1,380 @@
...
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, eventID) => {
+						if (!err) {
+							var booking_obj = {
+								userID: userID,
+								eventID: eventID[0].id,
+								slotHall: slotHall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 99]
```diff
@@ -0,0 +1,380 @@
...
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 100]
```diff
@@ -0,0 +1,380 @@
...
+			requirements: requirements,
+			details: details,
+			dateWanted: dateWanted,
+			userID: userID
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 101]
```diff
@@ -0,0 +1,380 @@
...
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			dateWanted: dateWanted,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 102]
```diff
@@ -0,0 +1,380 @@
...
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 76 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 103]
```diff
@@ -0,0 +1,380 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 104]
```diff
@@ -0,0 +1,380 @@
...
+			for (var j = 1; j <= 9; j++) {
+				if (req.body[`cell${j}${i}`]) {
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'event_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 79 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 105]
```diff
@@ -0,0 +1,380 @@
...
+								con.query(
+									"delete from booking where id =?",
+									req.body.booking_id,
+									(err, result) => {
+										if (!err) {
+											console.log(
+												`${req.body.booking_id} is deleted`
+											);
+											res.send(JSON.stringify(result));
+										} else
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 57 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 106]
```diff
@@ -0,0 +1,380 @@
...
+		};
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, eventID) => {
+						if (!err) {
+							var booking_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 107]
```diff
@@ -0,0 +1,380 @@
...
+			);
+		} else if (req.body.type === "reject") {
+			con.query(
+				'update booking set status="Rejected" where id = ?',
+				req.body.booking_id,
+				(err, result) => {
+					if (!err) {
+						console.log(`${req.body.booking_id} is rejected`);
+						res.send(JSON.stringify(result));
+					} else res.send(JSON.stringify(err.code));
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'else'. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 108]
```diff
@@ -0,0 +1,380 @@
...
+				(err, result) => {
+					if (!err) {
+						console.log(`${req.body.booking_id} is approved`);
+						res.send(JSON.stringify(result));
+					} else res.send(JSON.stringify(err.code));
+				}
+			);
+		} else if (req.body.type === "reject") {
+			con.query(
+				'update booking set status="Rejected" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 109]
```diff
@@ -0,0 +1,380 @@
...
+				if (req.body[`cell${j}${i}`]) {
+					slotHall += j.toString() + i.toString();
+				}
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 110]
```diff
@@ -0,0 +1,380 @@
...
+	if (req.session.user) {
+		con.query(
+			"select eventID from booking where id = ?",
+			req.body.booking_id,
+			(err, result) => {
+				if (result) {
+					con.query(
+						"delete from events where id = ?",
+						result[0].eventID,
+						err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 111]
```diff
@@ -0,0 +1,380 @@
...
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
+			dateWanted: dateWanted,
+			userID: userID
+		};
+		con.query("insert into events set ?", event_obj, err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 112]
```diff
@@ -0,0 +1,380 @@
...
+});
+app.post("/onLogin", (req, res) => {
+	var username = req.body.username;
+	var password = req.body.password;
+	con.query(
+		"select * from users where username='" + username + "';",
+		(err, rows) => {
+			if (!err) {
+				if (rows.length > 0) {
+					if (
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Potential timing attack, left side: true (security/detect-possible-timing-attacks)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 113]
```diff
@@ -0,0 +1,380 @@
...
+		con.query("insert into events set ?", event_obj, err => {
+			if (!err) {
+				console.log(`Inserted ${event_obj.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, eventID) => {
+						if (!err) {
+							var booking_obj = {
+								userID: userID,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 114]
```diff
@@ -0,0 +1,380 @@
...
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateStatus", (req, res) => {
+	console.log(req.body.type);
+	if (req.session.user) {
+		if (req.body.type === "approve") {
+			con.query(
+				'update booking set status="Approved" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 115]
```diff
@@ -0,0 +1,380 @@
...
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var userID = req.session.user.id;
+		var dateWanted = req.body.dateWanted;
+		var slotHall = "";
+		for (var i = 1; i <= 7; i++)
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'for' condition. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 116]
```diff
@@ -0,0 +1,380 @@
...
+			}
+		var club = req.body.club_name;
+		var details = req.body.desc;
+		var title = req.body.event_name;
+		var requirements = req.body.requirements;
+		var event_obj = {
+			title: title,
+			club: club,
+			requirements: requirements,
+			details: details,
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 10
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 117]
```diff
@@ -0,0 +1,385 @@
...
+	if (req.session.user) {
+		con.query(
+			"select eventID from booking where id = ?",
+			req.body.booking_id,
+			(err, result) => {
+				if (result) {
+					con.query(
+						"delete from events where id = ?",
+						result[0].eventID,
+						err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 118]
```diff
@@ -0,0 +1,385 @@
...
+		};
+		con.query("insert into events set ?", eventPayload, err => {
+			if (!err) {
+				console.log(`Inserted ${eventPayload.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, eventID) => {
+						if (!err) {
+							var booking_obj = {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 119]
```diff
@@ -0,0 +1,385 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 120]
```diff
@@ -0,0 +1,385 @@
...
+				console.log(`Inserted ${eventPayload.title} into events.`);
+				con.query(
+					"select id from events WHERE userID= ? ORDER BY id DESC LIMIT 1",
+					req.session.user.id,
+					(err, eventID) => {
+						if (!err) {
+							var booking_obj = {
+								userID: req.session.user.id,
+								eventID: eventID[0].id,
+								slotHall: slotHall
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected property shorthand. (object-shorthand)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 121]
```diff
@@ -0,0 +1,385 @@
...
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateStatus", (req, res) => {
+	if (req.session.user) {
+		if (req.body.type === "approve") {
+			con.query(
+				'update booking set status="Approved" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 122]
```diff
@@ -0,0 +1,385 @@
...
+			}
+		var eventPayload = {
+			title: req.body.event_name,
+			club: req.body.clubName,
+			requirements: req.body.requirements,
+			details: req.body.desc,
+			dateWanted: req.body.dateWanted,
+			userID: req.session.user.id
+		};
+		con.query("insert into events set ?", eventPayload, err => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected parentheses around arrow function argument. (arrow-parens)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 123]
```diff
@@ -0,0 +1,385 @@
...
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
+	if (req.session.user) {
+		var slotHall = "";
+		for (var i = 1; i <= 7; i++)
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Expected { after 'for' condition. (curly)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 124]
```diff
@@ -0,0 +1,385 @@
...
+								eventID: eventID[0].id,
+								slotHall: slotHall
+							};
+							con.query(
+								"insert into booking set ?",
+								booking_obj,
+								err => {
+									if (!err) {
+										console.log(
+											`Inserted event with id ${booking_obj.eventID} into booking.`
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Identifier 'booking_obj' is not in camel case. (camelcase)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 125]
```diff
@@ -0,0 +1,385 @@
...
+						console.log(`${req.body.booking_id} is approved`);
+						res.send(JSON.stringify(result));
+					} else {
+						res.send(JSON.stringify(err.code));
+					}
+				}
+			);
+		} else if (req.body.type === "reject") {
+			con.query(
+				'update booking set status="Rejected" where id = ?',
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Strings must use doublequote. (quotes)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 126]
```diff
@@ -0,0 +1,385 @@
...
+	}
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else {
+		res.render("login");
+	}
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Hall-Management-System/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 127]
```diff
@@ -0,0 +1,447 @@
...
+				res.status(500).render("error", {
+					errorMessage: "Inserting into event failed!"
+				});
+			}
+		});
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/updateBooking", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 128]
```diff
@@ -0,0 +1,447 @@
...
+	}
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else {
+		res.render("login");
+	}
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 129]
```diff
@@ -0,0 +1,447 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 130]
```diff
@@ -0,0 +1,423 @@
...
+	}
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else {
+		res.render("login");
+	}
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 131]
```diff
@@ -0,0 +1,423 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 132]
```diff
@@ -0,0 +1,423 @@
...
+		// }
+		var eventPayload = {
+			title: req.body.event_name,
+			club: req.body.clubName,
+			requirements: req.body.requirements,
+			details: req.body.desc,
+			dateWanted: req.body.dateWanted,
+			userID: req.session.user.id
+		};
+		console.log({eventPayload}, req.body.bookingID)
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Missing semicolon. (semi)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 133]
```diff
@@ -0,0 +1,418 @@
...
+	}
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else {
+		res.render("login");
+	}
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 134]
```diff
@@ -0,0 +1,418 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 135]
```diff
@@ -0,0 +1,418 @@
...
+				res.status(500).render("error", {
+					errorMessage: "Inserting into event failed!"
+				});
+			}
+		});
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/onRequestUpdate", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js [hunk 136]
```diff
@@ -0,0 +1,426 @@
...
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 137]
```diff
@@ -0,0 +1,426 @@
...
+	}
+});
+app.get("/login", (req, res) => {
+	if (req.session.user) {
+		res.redirect("/dashboard");
+	} else {
+		res.render("login");
+	}
+});
+app.get("/dashboard", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js [hunk 138]
```diff
@@ -0,0 +1,426 @@
...
+						errorMessage: "Availability checking failed!"
+					});
+				}
+			}
+		);
+	} else {
+		res.redirect("/login");
+	}
+});
+app.post("/makeRequest", (req, res) => {
```
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js (hunk 136 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 138 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 137 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js (hunk 136 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 138 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 137 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 3
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)

File: index.js (hunk 136 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 137 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

File: index.js (hunk 138 above)
Comment (aravindvnair99) [inline index.js]: Codacy Issue found: [Arrow function has a complexity of 5. (complexity)](https://app.codacy.com/app/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231)

**Comment by aravindvnair99** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- index.js  5
         

Clones added
============
- index.js  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/AravindVNair99/Hall-Management-System/pullRequest?prid=4592231&bid=15419072)
